framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_SENDER)%'

    notifier:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email', 'chat/slack']
            high: ['email', 'chat/slack']
            medium: ['email', 'chat/slack']
            low: ['email', 'chat/slack']
        admin_recipients:
            - { email: '%env(RECIPIENT_EMAIL)%' }
        chatter_transports:
            slack: '%env(SLACK_DSN)%'