version: '3.5'

services:
  nginx:
    image: 'nginx:1.19-alpine'
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  memcached:
    image: memcached

  database:
    image: 'mysql:8.0'
    volumes:
      - ./docker/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "5432:5432"

  rabbit:
    image: 'rabbitmq:3.9.13-management-alpine'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/log/:/var/log/rabbitmq/

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - memcached
      - database
      - rabbit
    environment:
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      SLACK_DSN: ${SLACK_DSN}
      MEMCACHED_HOST: memcached
      DATABASE_URL: "mysql://root:${MYSQL_ROOT_PASSWORD}@database:5432/${MYSQL_DATABASE}"
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}

