version: '3.5'

services:
  nginx:
    image: 'nginx:1.19-alpine'
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  memcached:
    image: memcached

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    volumes:
      - ./docker/database:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-debricked}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-debricked}
    ports:
      - "5432:5432"

  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

  rabbit:
    image: 'rabbitmq:3.9.13-management-alpine'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/log/:/var/log/rabbitmq/

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - memcached
      - database
      - rabbit
      - mailer
    environment:
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      SLACK_DSN: ${SLACK_DSN}
      MEMCACHED_HOST: memcached
      DATABASE_URL: "postgresql://${POSTGRES_USER:-debricked}:${POSTGRES_PASSWORD:-ChangeMe}@database:5432/${POSTGRES_DB:-debricked}?serverVersion=${POSTGRES_VERSION:-13}&charset=utf8"
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DEBRICKED_API_TOKEN: ${DEBRICKED_API_TOKEN}
      MAILER_DSN: ${MAILER_DSN}
      MAILER_SENDER: ${MAILER_SENDER}
